// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dea.prototipo.web;

import com.dea.prototipo.web.ForgotPasswordForm;

privileged aspect ForgotPasswordForm_Roo_JavaBean {
    
    public String ForgotPasswordForm.getEmail() {
        return this.email;
    }
    
    public void ForgotPasswordForm.setEmail(String email) {
        this.email = email;
    }
    
}
