// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dea.prototipo.domain;

import com.dea.prototipo.domain.Bodega;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Bodega_Roo_Configurable {
    
    declare @type: Bodega: @Configurable;
    
}
